#language: generic
sudo: required
services: 
  - docker

before_install;
  - docker build -t dba1701a/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dba1701a/docker-react npm run test 

  


