version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
#      - ./node_modules:/app/node_modules
      - ./app/node_modules
      - .:/app

