FROM node:16-alpine

WORKDIR '/app'

COPY package.json .
#RUN npm install -g npm@8.13.2
#RUN npm install --location=global npm@8.13.2
RUN npm install --location=global npm@8.1.3

COPY . .

CMD ["npm", "run", "start"]


